pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                script {
                    // Convert Windows path to Unix path
                    def workspacePath = "${env.WORKSPACE}".replaceAll("\\\\", "/").replaceAll("C:", "/c")
                    
                    docker.image('node:16-alpine').inside("-v ${workspacePath}:/workspace -w /workspace") {
                        sh 'node --version'
                    }
                }
            }
        }
    }
}
