pipeline {
  agent any
  stages {
    stage('Test') {
      steps {
        script {
          docker.image('node:16-alpine').inside('-v /c/ProgramData/Jenkins/.jenkins/workspace/test-project:/workspace -w /workspace') {
            sh 'node --version'
          }
        }
      }
    }
  }
}
