pipeline {
  agent {
    docker { 
      image 'node:16-alpine' 
      args '-v /c/ProgramData/Jenkins/.jenkins/workspace/test-project:/workspace -w /workspace'
    }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
  }
}
